version: "3.3"

services:
  web:
    build: .
    image: taskify
    volumes:
      - ./taskify:/usr/src/app/
    ports:
      - 8000:8000

  migration:
    build: .
    image: taskify
    command: migrate --noinput
    volumes:
      - ./taskify:/usr/src/app/
    depends_on:
      - db

  db:
    image: docker.arvancloud.ir/postgres:16.1-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ./dist/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
