version: "3.3"

services:
  web:
    build: .
    image: taskify
    command: runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      migration:
        condition: service_completed_successfully

  migration:
    build: .
    image: taskify
    command: migrate --noinput
    volumes:
      - .:/usr/src/app/
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.arvancloud.ir/postgres:16.1-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ./dist/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
