# Generated by Django 4.2.7 on 2023-11-14 14:21

from django.db import migrations, models

import taskify.validators.json_schema_validator


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            ("Created", "Created"),
                            ("Opened", "Opened"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Created",
                    ),
                ),
                (
                    "dynamic_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            taskify.validators.json_schema_validator.JSONSchemaValidator(
                                {
                                    "items": {
                                        "oneOf": [
                                            {
                                                "additionalProperties": False,
                                                "properties": {
                                                    "name": {"type": "string"},
                                                    "type": {"const": "int"},
                                                    "value": {"type": "integer"},
                                                },
                                            },
                                            {
                                                "additionalProperties": False,
                                                "properties": {
                                                    "name": {"type": "string"},
                                                    "type": {"const": "text"},
                                                    "value": {"type": "string"},
                                                },
                                            },
                                            {
                                                "additionalProperties": False,
                                                "properties": {
                                                    "name": {"type": "string"},
                                                    "type": {"const": "date"},
                                                    "value": {
                                                        "format": "date",
                                                        "type": "string",
                                                    },
                                                },
                                            },
                                        ],
                                        "required": ["name", "type", "value"],
                                        "type": "object",
                                    },
                                    "type": "array",
                                }
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
