# Generated by Django 4.2.7 on 2023-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Opened", "Opened"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Created",
                max_length=20,
            ),
        ),
    ]
