# Generated by Django 4.2.7 on 2023-11-16 13:54

from django.db import migrations, models
import taskify.validators.json_schema_validator


class Migration(migrations.Migration):
    dependencies = [
        ("taskify", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dynamic_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[
                    taskify.validators.json_schema_validator.JSONSchemaValidator(
                        {
                            "items": {
                                "oneOf": [
                                    {
                                        "additionalProperties": False,
                                        "properties": {
                                            "name": {"type": "string"},
                                            "type": {"const": "int"},
                                            "value": {"type": "integer"},
                                        },
                                    },
                                    {
                                        "additionalProperties": False,
                                        "properties": {
                                            "name": {"type": "string"},
                                            "type": {"const": "text"},
                                            "value": {"type": "string"},
                                        },
                                    },
                                    {
                                        "additionalProperties": False,
                                        "properties": {
                                            "name": {"type": "string"},
                                            "type": {"const": "date"},
                                            "value": {
                                                "format": "date",
                                                "type": "string",
                                            },
                                        },
                                    },
                                    {
                                        "additionalProperties": False,
                                        "properties": {
                                            "name": {"type": "string"},
                                            "type": {"const": "user"},
                                            "value": {"type": "string"},
                                        },
                                    },
                                ],
                                "required": ["name", "type", "value"],
                                "type": "object",
                            },
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
